// ~/Documents/dx/code/dxBridgeDemo/warden » protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative wardenpb/warden.proto
// python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. warden.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: wardenpb/warden.proto

package wardenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{0}
}

type GetCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification string `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
}

func (x *GetCredentialReq) Reset() {
	*x = GetCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialReq) ProtoMessage() {}

func (x *GetCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialReq.ProtoReflect.Descriptor instead.
func (*GetCredentialReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialReq) GetIdentification() string {
	if x != nil {
		return x.Identification
	}
	return ""
}

type GetCredentialResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Credential string `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *GetCredentialResp) Reset() {
	*x = GetCredentialResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCredentialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResp) ProtoMessage() {}

func (x *GetCredentialResp) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResp.ProtoReflect.Descriptor instead.
func (*GetCredentialResp) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{2}
}

func (x *GetCredentialResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetCredentialResp) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type AwsCredentialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification string `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
}

func (x *AwsCredentialReq) Reset() {
	*x = AwsCredentialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwsCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsCredentialReq) ProtoMessage() {}

func (x *AwsCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsCredentialReq.ProtoReflect.Descriptor instead.
func (*AwsCredentialReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{3}
}

func (x *AwsCredentialReq) GetIdentification() string {
	if x != nil {
		return x.Identification
	}
	return ""
}

type AwsCredentialResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKeyId     string `protobuf:"bytes,1,opt,name=accessKeyId,proto3" json:"accessKeyId,omitempty"`
	SecretAccessKey string `protobuf:"bytes,2,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"`
	Region          string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	KmsKeyId        string `protobuf:"bytes,4,opt,name=kmsKeyId,proto3" json:"kmsKeyId,omitempty"`
}

func (x *AwsCredentialResp) Reset() {
	*x = AwsCredentialResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwsCredentialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsCredentialResp) ProtoMessage() {}

func (x *AwsCredentialResp) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsCredentialResp.ProtoReflect.Descriptor instead.
func (*AwsCredentialResp) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{4}
}

func (x *AwsCredentialResp) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AwsCredentialResp) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AwsCredentialResp) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsCredentialResp) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

type SaveShareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Share                  string `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	OnboardAccountAddress  string `protobuf:"bytes,2,opt,name=onboardAccountAddress,proto3" json:"onboardAccountAddress,omitempty"`
	OffboardAccountAddress string `protobuf:"bytes,3,opt,name=offboardAccountAddress,proto3" json:"offboardAccountAddress,omitempty"`
}

func (x *SaveShareReq) Reset() {
	*x = SaveShareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveShareReq) ProtoMessage() {}

func (x *SaveShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveShareReq.ProtoReflect.Descriptor instead.
func (*SaveShareReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{5}
}

func (x *SaveShareReq) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *SaveShareReq) GetOnboardAccountAddress() string {
	if x != nil {
		return x.OnboardAccountAddress
	}
	return ""
}

func (x *SaveShareReq) GetOffboardAccountAddress() string {
	if x != nil {
		return x.OffboardAccountAddress
	}
	return ""
}

type ShareResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification string `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	Share          string `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
}

func (x *ShareResp) Reset() {
	*x = ShareResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareResp) ProtoMessage() {}

func (x *ShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareResp.ProtoReflect.Descriptor instead.
func (*ShareResp) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{6}
}

func (x *ShareResp) GetIdentification() string {
	if x != nil {
		return x.Identification
	}
	return ""
}

func (x *ShareResp) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

type GetWardenOnboardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash string `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxnHash   string `protobuf:"bytes,2,opt,name=txnHash,proto3" json:"txnHash,omitempty"`
}

func (x *GetWardenOnboardReq) Reset() {
	*x = GetWardenOnboardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardenOnboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardenOnboardReq) ProtoMessage() {}

func (x *GetWardenOnboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardenOnboardReq.ProtoReflect.Descriptor instead.
func (*GetWardenOnboardReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{7}
}

func (x *GetWardenOnboardReq) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *GetWardenOnboardReq) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

type GetWardenOnboardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId    uint64 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	RealAmount uint64 `protobuf:"varint,2,opt,name=realAmount,proto3" json:"realAmount,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	GasPrice   uint64 `protobuf:"varint,4,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Nonce      uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Share      string `protobuf:"bytes,6,opt,name=share,proto3" json:"share,omitempty"`
	Contract   string `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`
	Fee        uint64 `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	IsEip1559  bool   `protobuf:"varint,9,opt,name=is_eip1559,json=isEip1559,proto3" json:"is_eip1559,omitempty"`
}

func (x *GetWardenOnboardResp) Reset() {
	*x = GetWardenOnboardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardenOnboardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardenOnboardResp) ProtoMessage() {}

func (x *GetWardenOnboardResp) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardenOnboardResp.ProtoReflect.Descriptor instead.
func (*GetWardenOnboardResp) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{8}
}

func (x *GetWardenOnboardResp) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetWardenOnboardResp) GetRealAmount() uint64 {
	if x != nil {
		return x.RealAmount
	}
	return 0
}

func (x *GetWardenOnboardResp) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetWardenOnboardResp) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *GetWardenOnboardResp) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetWardenOnboardResp) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *GetWardenOnboardResp) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *GetWardenOnboardResp) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *GetWardenOnboardResp) GetIsEip1559() bool {
	if x != nil {
		return x.IsEip1559
	}
	return false
}

type GetWardenOffboardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash string `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxnHash   string `protobuf:"bytes,2,opt,name=txnHash,proto3" json:"txnHash,omitempty"`
}

func (x *GetWardenOffboardReq) Reset() {
	*x = GetWardenOffboardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardenOffboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardenOffboardReq) ProtoMessage() {}

func (x *GetWardenOffboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardenOffboardReq.ProtoReflect.Descriptor instead.
func (*GetWardenOffboardReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{9}
}

func (x *GetWardenOffboardReq) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *GetWardenOffboardReq) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

type GetWardenOffboardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId    uint64 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	RealAmount uint64 `protobuf:"varint,2,opt,name=realAmount,proto3" json:"realAmount,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	GasPrice   uint64 `protobuf:"varint,4,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Nonce      uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Share      string `protobuf:"bytes,6,opt,name=share,proto3" json:"share,omitempty"`
	Contract   string `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`
	IsEip1559  bool   `protobuf:"varint,8,opt,name=is_eip1559,json=isEip1559,proto3" json:"is_eip1559,omitempty"`
}

func (x *GetWardenOffboardResp) Reset() {
	*x = GetWardenOffboardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardenOffboardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardenOffboardResp) ProtoMessage() {}

func (x *GetWardenOffboardResp) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardenOffboardResp.ProtoReflect.Descriptor instead.
func (*GetWardenOffboardResp) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{10}
}

func (x *GetWardenOffboardResp) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetWardenOffboardResp) GetRealAmount() uint64 {
	if x != nil {
		return x.RealAmount
	}
	return 0
}

func (x *GetWardenOffboardResp) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetWardenOffboardResp) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *GetWardenOffboardResp) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetWardenOffboardResp) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *GetWardenOffboardResp) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *GetWardenOffboardResp) GetIsEip1559() bool {
	if x != nil {
		return x.IsEip1559
	}
	return false
}

type OnboardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash      string `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxnHash        string `protobuf:"bytes,2,opt,name=txnHash,proto3" json:"txnHash,omitempty"`
	OnboardTxnHash string `protobuf:"bytes,3,opt,name=onboardTxnHash,proto3" json:"onboardTxnHash,omitempty"`
	Nonce          uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Batch          int64  `protobuf:"varint,5,opt,name=batch,proto3" json:"batch,omitempty"`
}

func (x *OnboardReq) Reset() {
	*x = OnboardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardReq) ProtoMessage() {}

func (x *OnboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardReq.ProtoReflect.Descriptor instead.
func (*OnboardReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{11}
}

func (x *OnboardReq) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *OnboardReq) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

func (x *OnboardReq) GetOnboardTxnHash() string {
	if x != nil {
		return x.OnboardTxnHash
	}
	return ""
}

func (x *OnboardReq) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *OnboardReq) GetBatch() int64 {
	if x != nil {
		return x.Batch
	}
	return 0
}

type OffboardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash       string `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxnHash         string `protobuf:"bytes,2,opt,name=txnHash,proto3" json:"txnHash,omitempty"`
	OffboardTxnHash string `protobuf:"bytes,3,opt,name=offboardTxnHash,proto3" json:"offboardTxnHash,omitempty"`
	Nonce           uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Batch           int64  `protobuf:"varint,5,opt,name=batch,proto3" json:"batch,omitempty"`
}

func (x *OffboardReq) Reset() {
	*x = OffboardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wardenpb_warden_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OffboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffboardReq) ProtoMessage() {}

func (x *OffboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_wardenpb_warden_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffboardReq.ProtoReflect.Descriptor instead.
func (*OffboardReq) Descriptor() ([]byte, []int) {
	return file_wardenpb_warden_proto_rawDescGZIP(), []int{12}
}

func (x *OffboardReq) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *OffboardReq) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

func (x *OffboardReq) GetOffboardTxnHash() string {
	if x != nil {
		return x.OffboardTxnHash
	}
	return ""
}

func (x *OffboardReq) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *OffboardReq) GetBatch() int64 {
	if x != nil {
		return x.Batch
	}
	return 0
}

var File_wardenpb_warden_proto protoreflect.FileDescriptor

var file_wardenpb_warden_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70,
	0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x26,
	0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22,
	0x3a, 0x0a, 0x10, 0x41, 0x77, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x11,
	0x41, 0x77, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x6d, 0x73, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x6d, 0x73, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x36,
	0x0a, 0x16, 0x6f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16,
	0x6f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x49, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f, 0x6e,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x6e, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68,
	0x22, 0xff, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f, 0x6e,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x66, 0x65, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x65, 0x69, 0x70, 0x31, 0x35, 0x35,
	0x39, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x45, 0x69, 0x70, 0x31, 0x35,
	0x35, 0x39, 0x22, 0x4e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f,
	0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x6e, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x6e, 0x48, 0x61,
	0x73, 0x68, 0x22, 0xee, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x6c,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x65, 0x69, 0x70, 0x31, 0x35,
	0x35, 0x39, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x45, 0x69, 0x70, 0x31,
	0x35, 0x35, 0x39, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x6e,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x78, 0x6e, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x22, 0x9b,
	0x01, 0x0a, 0x0b, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x78, 0x6e, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x32, 0xa6, 0x04, 0x0a,
	0x06, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x77, 0x73, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x70, 0x62, 0x2e, 0x41, 0x77, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x41,
	0x77, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12,
	0x16, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x0f, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x70, 0x62, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x53,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f, 0x6e, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14,
	0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x08, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x77, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wardenpb_warden_proto_rawDescOnce sync.Once
	file_wardenpb_warden_proto_rawDescData = file_wardenpb_warden_proto_rawDesc
)

func file_wardenpb_warden_proto_rawDescGZIP() []byte {
	file_wardenpb_warden_proto_rawDescOnce.Do(func() {
		file_wardenpb_warden_proto_rawDescData = protoimpl.X.CompressGZIP(file_wardenpb_warden_proto_rawDescData)
	})
	return file_wardenpb_warden_proto_rawDescData
}

var file_wardenpb_warden_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_wardenpb_warden_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: wardenpb.Empty
	(*GetCredentialReq)(nil),      // 1: wardenpb.GetCredentialReq
	(*GetCredentialResp)(nil),     // 2: wardenpb.GetCredentialResp
	(*AwsCredentialReq)(nil),      // 3: wardenpb.AwsCredentialReq
	(*AwsCredentialResp)(nil),     // 4: wardenpb.AwsCredentialResp
	(*SaveShareReq)(nil),          // 5: wardenpb.SaveShareReq
	(*ShareResp)(nil),             // 6: wardenpb.ShareResp
	(*GetWardenOnboardReq)(nil),   // 7: wardenpb.GetWardenOnboardReq
	(*GetWardenOnboardResp)(nil),  // 8: wardenpb.GetWardenOnboardResp
	(*GetWardenOffboardReq)(nil),  // 9: wardenpb.GetWardenOffboardReq
	(*GetWardenOffboardResp)(nil), // 10: wardenpb.GetWardenOffboardResp
	(*OnboardReq)(nil),            // 11: wardenpb.OnboardReq
	(*OffboardReq)(nil),           // 12: wardenpb.OffboardReq
}
var file_wardenpb_warden_proto_depIdxs = []int32{
	1,  // 0: wardenpb.Warden.GetCredential:input_type -> wardenpb.GetCredentialReq
	3,  // 1: wardenpb.Warden.GetAwsCredential:input_type -> wardenpb.AwsCredentialReq
	5,  // 2: wardenpb.Warden.SaveShare:input_type -> wardenpb.SaveShareReq
	0,  // 3: wardenpb.Warden.GetShare:input_type -> wardenpb.Empty
	7,  // 4: wardenpb.Warden.GetWardenOnboard:input_type -> wardenpb.GetWardenOnboardReq
	11, // 5: wardenpb.Warden.Onboard:input_type -> wardenpb.OnboardReq
	9,  // 6: wardenpb.Warden.GetWardenOffboard:input_type -> wardenpb.GetWardenOffboardReq
	12, // 7: wardenpb.Warden.Offboard:input_type -> wardenpb.OffboardReq
	2,  // 8: wardenpb.Warden.GetCredential:output_type -> wardenpb.GetCredentialResp
	4,  // 9: wardenpb.Warden.GetAwsCredential:output_type -> wardenpb.AwsCredentialResp
	0,  // 10: wardenpb.Warden.SaveShare:output_type -> wardenpb.Empty
	6,  // 11: wardenpb.Warden.GetShare:output_type -> wardenpb.ShareResp
	8,  // 12: wardenpb.Warden.GetWardenOnboard:output_type -> wardenpb.GetWardenOnboardResp
	0,  // 13: wardenpb.Warden.Onboard:output_type -> wardenpb.Empty
	10, // 14: wardenpb.Warden.GetWardenOffboard:output_type -> wardenpb.GetWardenOffboardResp
	0,  // 15: wardenpb.Warden.Offboard:output_type -> wardenpb.Empty
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_wardenpb_warden_proto_init() }
func file_wardenpb_warden_proto_init() {
	if File_wardenpb_warden_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wardenpb_warden_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCredentialResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwsCredentialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwsCredentialResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveShareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardenOnboardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardenOnboardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardenOffboardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardenOffboardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnboardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wardenpb_warden_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OffboardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wardenpb_warden_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wardenpb_warden_proto_goTypes,
		DependencyIndexes: file_wardenpb_warden_proto_depIdxs,
		MessageInfos:      file_wardenpb_warden_proto_msgTypes,
	}.Build()
	File_wardenpb_warden_proto = out.File
	file_wardenpb_warden_proto_rawDesc = nil
	file_wardenpb_warden_proto_goTypes = nil
	file_wardenpb_warden_proto_depIdxs = nil
}
